export const LIST_CATE_REQUEST = 'LIST_CATE_REQUEST';
export const LIST_CATE_SUCCESS = 'LIST_CATE_SUCCESS';
export const DELETE_CATE = 'DELETE_CATE';
export const ADD_CATE = 'ADD_CATE';
export const EDIT_CATE = 'EDIT_CATE';
export const LIST_PRODUCT_REQUEST = 'LIST_PRODUCT_REQUEST';
export const LIST_PRODUCT_SUCCESS = 'LIST_PRODUCT_SUCCESS';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_CATE_SUCCESS = 'PRODUCT_CATE_SUCCESS';
export const PRODUCT_CATE_REQUEST = 'PRODUCT_CATE_REQUEST';
export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
export const PRODUCT_SAVE ='PRODUCT_SAVE';
export const PRODUCT_ADD = 'PRODUCT_ADD';
export const PRODUCT_ADD_CART = 'PRODUCT_ADD_CART';
//Post
export const LIST_CATE_POST_REQUEST = 'LIST_CATE_POST_REQUEST';
export const LIST_CATE_POST_SUCCESS = 'LIST_CATE_POST_SUCCESS';
export const DELETE_CATE_POST = 'DELETE_CATE_POST';
export const ADD_CATE_POST = 'ADD_CATE_POST';
export const EDIT_CATE_POST = 'EDIT_CATE_POST';
////-----------------
export const LIST_POST_SUCCESS = 'LIST_POST_SUCCESS';
export const LIST_POST_REQUESST = 'LIST_POST_REQUESST';
export const LIST_POST_DETAILS_REQUESST = 'LIST_POST_DETAILS_REQUESST';
export const LIST_POST_DETAILS_SUCCESS = 'LIST_POST_DETAILS_SUCCESS';
export const LIST_POST_CATE_SUCCESS = 'LIST_POST_CATE_SUCCESS';
export const LIST_POST_CATE_REQUESST = 'LIST_POST_CATE_REQUESST';
export const POST_ADD = 'POST_ADD';
export const POST_EDIT = 'POST_EDIT';
export const POST_DELETE = 'POST_DELETE';
//----------------Login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const LOGIN_ADMIN_REQUEST = 'LOGIN_ADMIN_REQUEST';